name = "filmi-server"
main = "src/index.ts"
compatibility_date = "2024-04-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODA4YTFiN2ItZTk4MC00NTUzLWE3MWYtMWRhMjJlOGY0MGE2IiwidGVuYW50X2lkIjoiNTM5ODlhYjYxMjVhMjM1MTZhNDM4ZjMyZjBlMzVmN2ZmMzU0MDBiM2EyYWU1YjIyMmUwMzUxNWNhNzJiM2QyMCIsImludGVybmFsX3NlY3JldCI6Ijc1NWVmMTk3LWUxNjctNDk1OC1iMTFlLTEzOTExNjg3NGYzNSJ9.quBBorhPcAhc2Sv20YRlEblZqfqxygVjaf-l0cVNF0E"

JWT_SECRET = "y*CGF/RYX6{#"